"""仓储接口层：服务层只依赖这些 Protocol，不感知底层数据库（SQLite / CloudBase PG HTTP API）。

方法签名只出现领域对象；SQL 与 pg_http 两个实现都遵循本接口。
"""
from __future__ import annotations

from datetime import date
from typing import Protocol

from app.domain.devices import DeviceGrant, DeviceRegistry
from app.domain.identity import User
from app.domain.licensing import ActivationCode


class UserRepo(Protocol):
    def get(self, username: str) -> User | None: ...
    def exists(self, username: str) -> bool: ...
    def create(self, user: User) -> User: ...
    def update_password(self, username: str, new_password_hash: str) -> None: ...
    def update_security(self, username: str, question: str, answer_hash: str) -> None: ...
    def update_theme(self, username: str, theme: str) -> None: ...
    def flush(self) -> None:
        """SQLite 下确保用户行已持久化（后续试用码 FK 依赖）；HTTP 后端无 FK 顺序问题，no-op。"""
        ...

    # ── 账号自助注销（account-deletion）：全部单语句 CAS，返回受影响行数 ──
    def request_deletion(self, username: str, requested_at, deadline, waive: bool) -> int:
        """受理注销申请。WHERE deletion_status='正常'；0 行=已在流程中（幂等）。"""
        ...
    def revoke_deletion(self, username: str, now) -> int:
        """撤销注销。WHERE status='注销撤销期' AND deadline>now；0 行=已到期或无申请。"""
        ...
    def mark_deleted(self, username: str, now) -> int:
        """到期执行标记（含 password_hash 置空）。WHERE status='注销撤销期' AND deadline<=now。"""
        ...
    def find_due_deletion_usernames(self, now) -> list[str]:
        """补偿扫描：deletion_status='注销撤销期' AND deadline<=now 的用户名。"""
        ...


class CodeRepo(Protocol):
    def get(self, code_id: str) -> ActivationCode | None: ...
    def find_all_by_username(self, username: str) -> list[ActivationCode]: ...
    def find_active_by_username(self, username: str) -> list[ActivationCode]: ...
    def find_all(self, limit: int = 200) -> list[ActivationCode]: ...
    def create(self, code: ActivationCode) -> None: ...
    def activate(self, code_id: str, username: str, expires_at: date) -> None: ...
    def revoke_unconsumed_for_user(self, username: str) -> int:
        """注销执行：该用户 unused/active（待激活+排队中+消耗中）全部置 revoked。返回行数。"""
        ...


class DeviceRepo(Protocol):
    def get_by_fingerprint(self, user_id: str, fingerprint: str) -> DeviceRegistry | None: ...
    def list_by_user(self, user_id: str) -> list[DeviceRegistry]: ...
    def upsert(self, device: DeviceRegistry) -> DeviceRegistry: ...
    def delete_by_id(self, device_id: str, user_id: str) -> bool: ...
    def delete_all_for_user(self, user_id: str) -> int:
        """注销执行：清空该用户全部设备绑定。返回行数。"""
        ...


class GrantRepo(Protocol):
    def get(self, pc_hash: str) -> DeviceGrant | None: ...
    def upsert(self, pc_hash: str, username: str, token: str, enrolled: bool, fingerprint: str) -> None: ...
    def set_enrolled(self, pc_hash: str, username: str, enrolled: bool) -> None: ...
    def delete_all_for_user(self, username: str) -> int:
        """注销执行：清空该用户全部设备授权。返回行数。"""
        ...


class ConfigRepo(Protocol):
    def get(self, key: str, default: str = "") -> str: ...
