"""仓储接口层：服务层只依赖这些 Protocol，不感知底层数据库（SQLite / CloudBase PG HTTP API）。

方法签名只出现领域对象；SQL 与 pg_http 两个实现都遵循本接口。
"""
from __future__ import annotations

from datetime import date
from typing import Protocol

from app.domain.devices import DeviceGrant, DeviceRegistry
from app.domain.identity import User
from app.domain.licensing import ActivationCode


class UserRepo(Protocol):
    def get(self, username: str) -> User | None: ...
    def exists(self, username: str) -> bool: ...
    def create(self, user: User) -> User: ...
    def update_password(self, username: str, new_password_hash: str) -> None: ...
    def update_security(self, username: str, question: str, answer_hash: str) -> None: ...
    def flush(self) -> None:
        """SQLite 下确保用户行已持久化（后续试用码 FK 依赖）；HTTP 后端无 FK 顺序问题，no-op。"""
        ...


class CodeRepo(Protocol):
    def get(self, code_id: str) -> ActivationCode | None: ...
    def find_all_by_username(self, username: str) -> list[ActivationCode]: ...
    def find_active_by_username(self, username: str) -> list[ActivationCode]: ...
    def find_all(self, limit: int = 200) -> list[ActivationCode]: ...
    def create(self, code: ActivationCode) -> None: ...
    def activate(self, code_id: str, username: str, expires_at: date) -> None: ...


class DeviceRepo(Protocol):
    def get_by_fingerprint(self, user_id: str, fingerprint: str) -> DeviceRegistry | None: ...
    def list_by_user(self, user_id: str) -> list[DeviceRegistry]: ...
    def upsert(self, device: DeviceRegistry) -> DeviceRegistry: ...
    def delete_by_id(self, device_id: str, user_id: str) -> bool: ...


class GrantRepo(Protocol):
    def get(self, pc_hash: str) -> DeviceGrant | None: ...
    def upsert(self, pc_hash: str, username: str, token: str, enrolled: bool, fingerprint: str) -> None: ...
    def set_enrolled(self, pc_hash: str, username: str, enrolled: bool) -> None: ...


class ConfigRepo(Protocol):
    def get(self, key: str, default: str = "") -> str: ...
